version: '3.8'

services:
  google-ads-mcp:
    build: .
    ports:
      - "7777:7777"
    env_file:
      - .env
    environment:
      # Google Cloud credentials (option 1 - Application Default Credentials)
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    
    # Mount credentials file
    volumes:
      - ${GOOGLE_CREDENTIALS_HOST_PATH:-./credentials.json}:/app/credentials.json:ro
    
    # Use fastmcp for proper MCP server
    command: fastmcp run google_ads_mcp_server.py --transport http --host 0.0.0.0 --port 7777
    
    # Restart policy
    restart: unless-stopped
    
    # Health check for HTTP wrapper
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7777/health"]
      interval: 30s
      timeout: 10s
      retries: 3
